import type { GeneratedPresentation } from "@/types";

// Brand colors — pptxgenjs uses hex WITHOUT the # prefix
const C = {
  bg: "040e0e",
  bgSlide: "071212",
  brand: "1E9AA0",
  brandDark: "167a7f",
  brandLight: "27b5bc",
  white: "f1f5f9",
  muted: "94a3b8",
  black: "000000",
};

export async function buildPptx(
  presentation: GeneratedPresentation,
): Promise<Buffer> {
  const PptxGenJS = (await import("pptxgenjs")).default;
  const pptx = new PptxGenJS();

  pptx.layout = "LAYOUT_WIDE"; // 13.33 x 7.5 inches (16:9)
  pptx.title = presentation.title;
  pptx.author = "StudyMind AI";

  // -- Title slide --
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: C.bg };

  // Glow backdrop behind title text
  titleSlide.addShape(pptx.ShapeType.rect, {
    x: 0.5,
    y: 2.3,
    w: 12.33,
    h: 3.0,
    fill: { color: C.brand, transparency: 88 },
    line: { color: C.brand, transparency: 60, width: 1 },
  });

  // Top accent bar
  titleSlide.addShape(pptx.ShapeType.rect, {
    x: 0,
    y: 0,
    w: "100%",
    h: 0.06,
    fill: { color: C.brand },
    line: { color: C.brand, width: 0 },
  });

  // Brand dot + label (top-left)
  titleSlide.addText("StudyMind AI", {
    x: 0.45,
    y: 0.12,
    w: 2.5,
    h: 0.28,
    fontSize: 9,
    bold: true,
    color: C.brandLight,
  });

  // Main title
  titleSlide.addText(presentation.title, {
    x: 0.8,
    y: 2.55,
    w: 11.73,
    h: 1.4,
    fontSize: 34,
    bold: true,
    color: C.white,
    align: "center",
    wrap: true,
    valign: "middle",
  });

  // Subtitle
  titleSlide.addText("Generated by StudyMind AI", {
    x: 0.8,
    y: 4.05,
    w: 11.73,
    h: 0.45,
    fontSize: 14,
    color: C.brandLight,
    align: "center",
  });

  // Date
  const dateStr = new Date(presentation.generatedAt).toLocaleDateString(
    "en-US",
    {
      year: "numeric",
      month: "long",
      day: "numeric",
    },
  );
  titleSlide.addText(dateStr, {
    x: 0.8,
    y: 4.58,
    w: 11.73,
    h: 0.3,
    fontSize: 10,
    color: C.muted,
    align: "center",
  });

  // Slide count badge
  titleSlide.addText(`${presentation.slides.length} slides`, {
    x: 0.8,
    y: 5.1,
    w: 11.73,
    h: 0.28,
    fontSize: 9,
    color: C.muted,
    align: "center",
  });

  // Bottom accent bar
  titleSlide.addShape(pptx.ShapeType.rect, {
    x: 0,
    y: 7.1,
    w: "100%",
    h: 0.05,
    fill: { color: C.brand },
    line: { color: C.brand, width: 0 },
  });

  // -- Content slides --
  for (const slide of presentation.slides) {
    const s = pptx.addSlide();
    s.background = { color: C.bgSlide };

    // Title area background strip
    s.addShape(pptx.ShapeType.rect, {
      x: 0,
      y: 0,
      w: "100%",
      h: 1.28,
      fill: { color: C.bg },
      line: { color: C.black, width: 0 },
    });

    // Left brand accent bar
    s.addShape(pptx.ShapeType.rect, {
      x: 0.35,
      y: 0.18,
      w: 0.055,
      h: 0.88,
      fill: { color: C.brand },
      line: { color: C.brand, width: 0 },
    });

    // Slide title
    s.addText(slide.title, {
      x: 0.6,
      y: 0.18,
      w: 11.6,
      h: 0.9,
      fontSize: 22,
      bold: true,
      color: C.white,
      valign: "middle",
      wrap: true,
    });

    // Slide number badge (top-right)
    s.addShape(pptx.ShapeType.roundRect, {
      x: 12.35,
      y: 0.13,
      w: 0.72,
      h: 0.38,
      rectRadius: 0.05,
      fill: { color: C.brand, transparency: 75 },
      line: { color: C.brand, transparency: 40, width: 1 },
    });
    s.addText(`${slide.slideNumber}`, {
      x: 12.35,
      y: 0.13,
      w: 0.72,
      h: 0.38,
      fontSize: 11,
      bold: true,
      color: C.brandLight,
      align: "center",
      valign: "middle",
    });

    // Divider line under title
    s.addShape(pptx.ShapeType.line, {
      x: 0.35,
      y: 1.28,
      w: 12.63,
      h: 0,
      line: { color: C.brandDark, width: 1, transparency: 20 },
    });

    // Bullet points
    const bulletItems = slide.bullets.map((bullet) => ({
      text: `  ${bullet}`,
      options: {
        bullet: { characterCode: "25B8", color: C.brand },
        fontSize: 15,
        color: C.white,
        paraSpaceBefore: 8,
        paraSpaceAfter: 8,
      },
    }));

    s.addText(bulletItems, {
      x: 0.55,
      y: 1.45,
      w: 12.23,
      h: 5.7,
      valign: "top",
      wrap: true,
    });

    // Bottom accent bar
    s.addShape(pptx.ShapeType.rect, {
      x: 0,
      y: 7.1,
      w: "100%",
      h: 0.05,
      fill: { color: C.brandDark, transparency: 40 },
      line: { color: C.brandDark, width: 0 },
    });

    // Footer label
    s.addText("StudyMind AI", {
      x: 11.3,
      y: 7.15,
      w: 1.85,
      h: 0.28,
      fontSize: 7,
      color: C.muted,
      align: "right",
    });
  }

  const arrayBuffer = (await pptx.write({
    outputType: "arraybuffer",
  })) as ArrayBuffer;
  return Buffer.from(arrayBuffer);
}
