import type { GeneratedPresentation, PPTTemplate } from "@/types";

// Color palettes — pptxgenjs uses hex WITHOUT the # prefix
type Palette = {
  bg: string;         // title slide bg
  bgSlide: string;    // content slide background
  titleStrip: string; // title strip bg on content slides (always dark/colored for white text contrast)
  brand: string;
  brandDark: string;
  brandLight: string;
  text: string;       // body / bullet text (changes per theme)
  muted: string;
};

const PALETTES: Record<PPTTemplate, Palette> = {
  default: {
    bg: "040e0e",
    bgSlide: "071212",
    titleStrip: "040e0e",
    brand: "1E9AA0",
    brandDark: "167a7f",
    brandLight: "27b5bc",
    text: "f1f5f9",
    muted: "94a3b8",
  },
  light: {
    bg: "f0fdfa",
    bgSlide: "ffffff",
    titleStrip: "0d9488",
    brand: "0d9488",
    brandDark: "0f766e",
    brandLight: "14b8a6",
    text: "0f172a",
    muted: "475569",
  },
  dark: {
    bg: "0f172a",
    bgSlide: "1e293b",
    titleStrip: "0f172a",
    brand: "6366f1",
    brandDark: "4f46e5",
    brandLight: "818cf8",
    text: "e2e8f0",
    muted: "94a3b8",
  },
};

// Text on titleStrip and top accent bars is always light (strips are always dark/colored)
const TITLE_TEXT = "f1f5f9";

export async function buildPptx(
  presentation: GeneratedPresentation,
  template: PPTTemplate = "default",
): Promise<Buffer> {
  const p = PALETTES[template] ?? PALETTES.default;

  const PptxGenJS = (await import("pptxgenjs")).default;
  const pptx = new PptxGenJS();

  pptx.layout = "LAYOUT_WIDE"; // 13.33 x 7.5 inches (16:9)
  pptx.title = presentation.title;
  pptx.author = "StudyMind";

  // -- Title slide --
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: p.bg };

  // Glow backdrop behind title text
  titleSlide.addShape(pptx.ShapeType.rect, {
    x: 0.5,
    y: 2.3,
    w: 12.33,
    h: 3.0,
    fill: { color: p.brand, transparency: 88 },
    line: { color: p.brand, transparency: 60, width: 1 },
  });

  // Top accent bar
  titleSlide.addShape(pptx.ShapeType.rect, {
    x: 0,
    y: 0,
    w: "100%",
    h: 0.06,
    fill: { color: p.brand },
    line: { color: p.brand, width: 0 },
  });

  // Brand dot + label (top-left)
  titleSlide.addText("StudyMind", {
    x: 0.45,
    y: 0.12,
    w: 2.5,
    h: 0.28,
    fontSize: 9,
    bold: true,
    color: p.brandLight,
  });

  // Main title
  titleSlide.addText(presentation.title, {
    x: 0.8,
    y: 2.55,
    w: 11.73,
    h: 1.4,
    fontSize: 34,
    bold: true,
    color: p.text,
    align: "center",
    wrap: true,
    valign: "middle",
  });

  // Subtitle
  titleSlide.addText("Generated by StudyMind", {
    x: 0.8,
    y: 4.05,
    w: 11.73,
    h: 0.45,
    fontSize: 14,
    color: p.brandLight,
    align: "center",
  });

  // Date
  const dateStr = new Date(presentation.generatedAt).toLocaleDateString(
    "en-US",
    {
      year: "numeric",
      month: "long",
      day: "numeric",
    },
  );
  titleSlide.addText(dateStr, {
    x: 0.8,
    y: 4.58,
    w: 11.73,
    h: 0.3,
    fontSize: 10,
    color: p.muted,
    align: "center",
  });

  // Slide count badge
  titleSlide.addText(`${presentation.slides.length} slides`, {
    x: 0.8,
    y: 5.1,
    w: 11.73,
    h: 0.28,
    fontSize: 9,
    color: p.muted,
    align: "center",
  });

  // Bottom accent bar
  titleSlide.addShape(pptx.ShapeType.rect, {
    x: 0,
    y: 7.1,
    w: "100%",
    h: 0.05,
    fill: { color: p.brand },
    line: { color: p.brand, width: 0 },
  });

  // -- Content slides --
  for (const slide of presentation.slides) {
    const s = pptx.addSlide();
    s.background = { color: p.bgSlide };

    // Title area background strip
    s.addShape(pptx.ShapeType.rect, {
      x: 0,
      y: 0,
      w: "100%",
      h: 1.28,
      fill: { color: p.titleStrip },
      line: { color: p.titleStrip, width: 0 },
    });

    // Left brand accent bar
    s.addShape(pptx.ShapeType.rect, {
      x: 0.35,
      y: 0.18,
      w: 0.055,
      h: 0.88,
      fill: { color: p.brand },
      line: { color: p.brand, width: 0 },
    });

    // Slide title
    s.addText(slide.title, {
      x: 0.6,
      y: 0.18,
      w: 11.6,
      h: 0.9,
      fontSize: 22,
      bold: true,
      color: TITLE_TEXT,
      valign: "middle",
      wrap: true,
    });

    // Slide number badge (top-right)
    s.addShape(pptx.ShapeType.roundRect, {
      x: 12.35,
      y: 0.13,
      w: 0.72,
      h: 0.38,
      rectRadius: 0.05,
      fill: { color: p.brand, transparency: 75 },
      line: { color: p.brand, transparency: 40, width: 1 },
    });
    s.addText(`${slide.slideNumber}`, {
      x: 12.35,
      y: 0.13,
      w: 0.72,
      h: 0.38,
      fontSize: 11,
      bold: true,
      color: p.brandLight,
      align: "center",
      valign: "middle",
    });

    // Divider line under title
    s.addShape(pptx.ShapeType.line, {
      x: 0.35,
      y: 1.28,
      w: 12.63,
      h: 0,
      line: { color: p.brandDark, width: 1, transparency: 20 },
    });

    // Bullet points
    const bulletItems = slide.bullets.map((bullet) => ({
      text: `  ${bullet}`,
      options: {
        bullet: { characterCode: "25B8", color: p.brand },
        fontSize: 15,
        color: p.text,
        paraSpaceBefore: 8,
        paraSpaceAfter: 8,
      },
    }));

    s.addText(bulletItems, {
      x: 0.55,
      y: 1.45,
      w: 12.23,
      h: 5.7,
      valign: "top",
      wrap: true,
    });

    // Bottom accent bar
    s.addShape(pptx.ShapeType.rect, {
      x: 0,
      y: 7.1,
      w: "100%",
      h: 0.05,
      fill: { color: p.brandDark, transparency: 40 },
      line: { color: p.brandDark, width: 0 },
    });

    // Footer label
    s.addText("StudyMind", {
      x: 11.3,
      y: 7.15,
      w: 1.85,
      h: 0.28,
      fontSize: 7,
      color: p.muted,
      align: "right",
    });
  }

  const arrayBuffer = (await pptx.write({
    outputType: "arraybuffer",
  })) as ArrayBuffer;
  return Buffer.from(arrayBuffer);
}
