"use client";

import { useState } from "react";
import type { GeneratedPresentation } from "@/types";

interface PPTDownloadButtonProps {
  presentation: GeneratedPresentation;
  fileName: string;
}

// Brand colors — pptxgenjs uses hex WITHOUT the # prefix
const C = {
  bg: "040e0e",
  bgSlide: "071212",
  brand: "1E9AA0",
  brandDark: "167a7f",
  brandLight: "27b5bc",
  white: "f1f5f9",
  muted: "94a3b8",
  black: "000000",
};

export default function PPTDownloadButton({
  presentation,
  fileName,
}: PPTDownloadButtonProps) {
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const safeName =
    fileName
      .replace(/\.[^.]+$/, "")
      .replace(/[^a-zA-Z0-9_\- ]/g, "")
      .trim()
      .replace(/\s+/g, "_") || presentation.title.replace(/\s+/g, "_");

  async function handleDownload() {
    setIsLoading(true);
    setError(null);

    try {
      // Generate entirely in the browser — avoids Vercel serverless limits
      const PptxGenJS = (await import("pptxgenjs")).default;
      const pptx = new PptxGenJS();

      pptx.layout = "LAYOUT_WIDE";
      pptx.title = presentation.title;
      pptx.author = "StudyMind AI";

      // -- Title slide --
      const titleSlide = pptx.addSlide();
      titleSlide.background = { color: C.bg };

      titleSlide.addShape(pptx.ShapeType.rect, {
        x: 0.5, y: 2.3, w: 12.33, h: 3.0,
        fill: { color: C.brand, transparency: 88 },
        line: { color: C.brand, transparency: 60, width: 1 },
      });
      titleSlide.addShape(pptx.ShapeType.rect, {
        x: 0, y: 0, w: "100%", h: 0.06,
        fill: { color: C.brand },
        line: { color: C.brand, width: 0 },
      });
      titleSlide.addText("StudyMind AI", {
        x: 0.45, y: 0.12, w: 2.5, h: 0.28,
        fontSize: 9, bold: true, color: C.brandLight,
      });
      titleSlide.addText(presentation.title, {
        x: 0.8, y: 2.55, w: 11.73, h: 1.4,
        fontSize: 34, bold: true, color: C.white,
        align: "center", wrap: true, valign: "middle",
      });
      titleSlide.addText("Generated by StudyMind AI", {
        x: 0.8, y: 4.05, w: 11.73, h: 0.45,
        fontSize: 14, color: C.brandLight, align: "center",
      });
      const dateStr = new Date(presentation.generatedAt).toLocaleDateString("en-US", {
        year: "numeric", month: "long", day: "numeric",
      });
      titleSlide.addText(dateStr, {
        x: 0.8, y: 4.58, w: 11.73, h: 0.3,
        fontSize: 10, color: C.muted, align: "center",
      });
      titleSlide.addText(`${presentation.slides.length} slides`, {
        x: 0.8, y: 5.1, w: 11.73, h: 0.28,
        fontSize: 9, color: C.muted, align: "center",
      });
      titleSlide.addShape(pptx.ShapeType.rect, {
        x: 0, y: 7.1, w: "100%", h: 0.05,
        fill: { color: C.brand },
        line: { color: C.brand, width: 0 },
      });

      // -- Content slides --
      for (const slide of presentation.slides) {
        const s = pptx.addSlide();
        s.background = { color: C.bgSlide };

        s.addShape(pptx.ShapeType.rect, {
          x: 0, y: 0, w: "100%", h: 1.28,
          fill: { color: C.bg },
          line: { color: C.black, width: 0 },
        });
        s.addShape(pptx.ShapeType.rect, {
          x: 0.35, y: 0.18, w: 0.055, h: 0.88,
          fill: { color: C.brand },
          line: { color: C.brand, width: 0 },
        });
        s.addText(slide.title, {
          x: 0.6, y: 0.18, w: 11.6, h: 0.9,
          fontSize: 22, bold: true, color: C.white,
          valign: "middle", wrap: true,
        });
        s.addShape(pptx.ShapeType.roundRect, {
          x: 12.35, y: 0.13, w: 0.72, h: 0.38,
          rectRadius: 0.05,
          fill: { color: C.brand, transparency: 75 },
          line: { color: C.brand, transparency: 40, width: 1 },
        });
        s.addText(`${slide.slideNumber}`, {
          x: 12.35, y: 0.13, w: 0.72, h: 0.38,
          fontSize: 11, bold: true, color: C.brandLight,
          align: "center", valign: "middle",
        });
        s.addShape(pptx.ShapeType.line, {
          x: 0.35, y: 1.28, w: 12.63, h: 0,
          line: { color: C.brandDark, width: 1, transparency: 20 },
        });

        const bulletItems = slide.bullets.map((bullet) => ({
          text: `  ${bullet}`,
          options: {
            bullet: { characterCode: "25B8", color: C.brand },
            fontSize: 15,
            color: C.white,
            paraSpaceBefore: 8,
            paraSpaceAfter: 8,
          },
        }));
        s.addText(bulletItems, {
          x: 0.55, y: 1.45, w: 12.23, h: 5.7,
          valign: "top", wrap: true,
        });

        s.addShape(pptx.ShapeType.rect, {
          x: 0, y: 7.1, w: "100%", h: 0.05,
          fill: { color: C.brandDark, transparency: 40 },
          line: { color: C.brandDark, width: 0 },
        });
        s.addText("StudyMind AI", {
          x: 11.3, y: 7.15, w: 1.85, h: 0.28,
          fontSize: 7, color: C.muted, align: "right",
        });
      }

      const blob = (await pptx.write({ outputType: "blob" })) as Blob;
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${safeName}.pptx`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Download failed.");
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <div className="flex flex-col items-end gap-1.5">
      <button
        onClick={handleDownload}
        disabled={isLoading}
        className="flex items-center gap-2 px-4 py-2 rounded-xl bg-brand/15 hover:bg-brand/25 border border-brand/25 text-brand-light text-sm font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
      >
        {isLoading ? (
          <>
            <svg className="w-4 h-4 animate-spin" viewBox="0 0 24 24" fill="none">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
            </svg>
            Preparing PPTX…
          </>
        ) : (
          <>
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            Download PPTX
          </>
        )}
      </button>
      {error && (
        <p className="text-xs text-rose-400 text-right max-w-[200px]">{error}</p>
      )}
    </div>
  );
}
